Fatal error: exception Failure("a already declared")